### ISSUE TITLE
Instance name should not contain "/"

### ISSUE THREAD

**Issue by t-woerner** [libre-server/rolekit#40]
The name of a role should not contain "/". This results in a trace back in the daemon or in rolectl for deferred deployments.

Maybe name should be alpha-num with some additional characters like '_', '-', '@', ..

**Comment by t-woerner** [comment]
This is the regular expression for instance name checking: ^[A-Za-z0-9][A-Za-z0-9_-.]*$
The instance name needs to start with a alpha-numeric character, then also '_', '-' and '.' are allowed.
The '.' is needed for the Domain Controller use case.

'@' is not allowed, it will collide with systemd.

**Comment by sgallagher** [comment]
That looks good to me.

Good catch on the `@` as well. Best not to get in the way with systemd.
