### ISSUE TITLE
Put instances in error state if it is transitional while roled starts

### ISSUE THREAD

**Issue by t-woerner** [libre-server/rolekit#45]
If roled was dying or killed while an instance is in a transitional state, then there is no way to change this state using rolekit interfaces. Not even a decommission --force is possible.

Proposal from Stephen: When roled starts, any role that is marked 'deploying' is immediately marked 'error'

**Comment by sgallagher** [comment]
We need to make sure that we mark these as "error" before we start answering requests from D-BUS or we might end up with race-conditions (marking a legitimately just-started deployment or decommission as an error)

**Comment by sgallagher** [comment]
(09:33:48 AM) twoerner: it should be simple to do in DBusRole.**init**
(09:34:01 AM) twoerner: after loading the role instance settings

**Comment by t-woerner** [comment]
This is not fixed completely, see [issue 52](https://github.com/libre-server/rolekit/issues/52)

**Comment by nphilipp** [comment]
Issue #52 is closed now, so I think that this one should be closed, too.
